# required minimum nextest version
nextest-version = "0.9.77"

[profile.default]
# A profile to run most tests, except tests that run longer than 10 seconds
default-filter = "not test(#*rate_limit_secondary) - test(#git::test::with_*)"

# This will flag any test that runs longer than 10 seconds. Useful when writing new tests.
slow-timeout = "10s"

[profile.ci]
# A profile to run only tests that use clang-tidy and/or clang-format
# NOTE: This profile is intended to keep CI runtime low. Locally, use default or all profiles

# This is all tests in tests/ folder + unit test for --extra-args.
default-filter = "kind(test) + test(#*use_extra_args)"

# show which tests were skipped
status-level = "skip"

# show log output from each test
success-output = "final"
failure-output = "immediate-final"

[profile.all]
# A profile to run all tests (including tests that run longer than 10 seconds)
default-filter = "all()"

# Revert slow-timeout to nextest default value.
# Otherwise, default profile value (10s) is inherited.
slow-timeout = "60s"
